### ISSUE TITLE
등록 버튼을 연달아 누르면 게시글이 중복 등록된다

### ISSUE THREAD

**Issue by sujin9** [woowacourse-teams/2023-edonymyeon#180]
## 📝 요약
글 작성 페이지에서 등록 버튼을 여러 번 누르면 게시글이 여러 개가 중복 등록됩니다.

## 🧪 재현 방법
이슈를 재현하기 위한 단계를 적어주세요.
1. 글 작성 버튼을 누른다.
2. 글을 작성한다.
3. 등록 버튼을 누르고, 화면이 이동하기 전 한 번 더 누른다.
4. 글이 두 개 등록되어있다.

## 👌 제안
응답이 올 때까지 등록 버튼을 못 누르게 하고, 로딩 중 표시를 보여줘면 되려나요 ~?

**Comment by rhkrwngud445** [comment]
sigleEventLisener 같은 것도 찾아보면 좋을 것 같아요~(적용이 됐었었나..?)
