### ISSUE TITLE
이리내 코드 똥을 치웁니다.

### ISSUE THREAD

**Issue by hectick** [woowacourse-teams/2023-edonymyeon#182]
## 📝 요약
MemberService에서 `@Transactional` 어노테이션을 빠뜨려 `@Transactional(readOnly=true)`가 적용되는 이슈 수정

**Comment by eunkeeee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이름이왜이럽니까
